// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VuCup_top.h for the primary calling header

#ifndef _VUCUP_TOP_CV32E41S_CSR__PI16_H_
#define _VUCUP_TOP_CV32E41S_CSR__PI16_H_  // guard

#include "verilated.h"
#include "VuCup_top__Dpi.h"

//==========

class VuCup_top__Syms;
class VuCup_top_VerilatedVcd;


//----------

VL_MODULE(VuCup_top_cv32e41s_csr__pi16) {
  public:
    
    // PORTS
    VL_IN8(rst_n,0,0);
    VL_IN8(clk,0,0);
    VL_IN8(scan_cg_en_i,0,0);
    VL_IN8(wr_en_i,0,0);
    VL_OUT8(rd_error_o,0,0);
    VL_IN(wr_data_i,31,0);
    VL_OUT(rd_data_o,31,0);
    
    // LOCAL SIGNALS
    CData/*0:0*/ __PVT__gen_hardened__DOT__clk_gated;
    CData/*0:0*/ __PVT__gen_hardened__DOT__core_clock_gate_i__DOT__clk_en;
    IData/*31:0*/ __PVT__rdata_q;
    IData/*31:0*/ __PVT__rdata_blk;
    IData/*31:0*/ __PVT__gen_hardened__DOT__shadow_q;
    
    // LOCAL VARIABLES
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__0__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__0__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__1__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__1__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__2__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__2__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__3__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__3__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__4__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__4__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__5__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__5__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__6__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__6__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__7__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__7__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__8__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__8__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__9__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__9__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__10__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__10__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__11__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__11__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__12__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__12__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__13__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__13__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__14__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__14__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__15__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__15__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__16__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__16__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__17__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__17__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__18__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__18__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__19__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__19__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__20__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__20__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__21__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__21__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__22__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__22__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__23__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__23__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__24__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__24__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__25__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__25__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__26__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__26__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__27__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__27__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__28__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__28__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__29__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__29__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__30__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__30__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__31__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffr_rdatareg__q_o;
    CData/*0:0*/ __Vcellout__gen_hardened__DOT__gen_csr__BRA__31__KET____DOT__gen_unmasked__DOT__gen_rv0__DOT__sffs_shadowreg__q_o;
    
    // INTERNAL VARIABLES
  private:
    VuCup_top__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(VuCup_top_cv32e41s_csr__pi16);  ///< Copying not allowed
  public:
    VuCup_top_cv32e41s_csr__pi16(const char* name = "TOP");
    ~VuCup_top_cv32e41s_csr__pi16();
    
    // INTERNAL METHODS
    void __Vconfigure(VuCup_top__Syms* symsp, bool first);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__0__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__17(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__10__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__27(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__11__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__28(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__12__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__29(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__13__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__30(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__14__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__31(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__15__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__32(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__1__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__18(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__2__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__19(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__3__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__20(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__4__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__21(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__5__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__22(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__6__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__23(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__7__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__24(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__8__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__25(VuCup_top__Syms* __restrict vlSymsp);
    void _combo__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__9__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__26(VuCup_top__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__0__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__33(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__10__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__43(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__11__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__44(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__12__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__45(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__13__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__46(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__14__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__47(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__15__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__48(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__1__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__34(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__2__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__35(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__3__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__36(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__4__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__37(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__5__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__38(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__6__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__39(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__7__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__40(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__8__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__41(VuCup_top__Syms* __restrict vlSymsp);
    void _sequent__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__9__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__42(VuCup_top__Syms* __restrict vlSymsp);
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__0__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__1(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__10__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__11(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__11__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__12(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__12__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__13(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__13__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__14(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__14__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__15(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__15__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__16(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__1__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__2(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__2__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__3(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__3__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__4(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__4__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__5(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__5__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__6(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__6__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__7(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__7__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__8(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__8__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__9(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    void _settle__TOP__uCup_top__DOT__genblk1__DOT__u_soc__DOT__u_core__DOT__cs_registers_i__DOT__csr_pmp__DOT__gen_pmp_csr__BRA__9__KET____DOT__pmp_region__DOT__pmp_addr_csr_i__10(VuCup_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
  private:
    static void traceInit(void* userp, VerilatedVcd* tracep, uint32_t code) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
